### ISSUE TITLE
Error when using spoof command in Ubuntu 16.04

### ISSUE THREAD

**Issue by paradox56** [feross/spoof#26]
Error when try to use spoof command in terminal 

```
spoof --help
/usr/local/lib/node_modules/spoof/bin/cmd.js:6
const { stripIndent } = require('common-tags')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by feross** [comment]
You need to update the version of Node.js you are using. It doesn't recognize the JS syntax being use.
