### ISSUE TITLE
-v flag throws error

### ISSUE THREAD

**Issue by juliuste** [feross/spoof#33]
First of all: Thank you very much for building and maintaining this package, it's very useful.

Today, I noticed what I assume to be a bug:

```bash
# Preparation
npm i -g spoof

# see the corresponding help message
spoof --help
# …
# spoof version | --version | -v          Show package version.
# …

# While these two lines work:
spoof version # (prints "2.0.1")
spoof --version # (prints "2.0.1")

# The following results in an error:
spoof -v
```

```
/usr/local/lib/node_modules/spoof/node_modules/minimist/index.js:65
            setKey(argv, x.split('.'), value);
                           ^

TypeError: x.split is not a function
    at /usr/local/lib/node_modules/spoof/node_modules/minimist/index.js:65:28
    at Array.forEach (<anonymous>)
    at setArg (/usr/local/lib/node_modules/spoof/node_modules/minimist/index.js:64:30)
    at module.exports (/usr/local/lib/node_modules/spoof/node_modules/minimist/index.js:179:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/spoof/bin/cmd.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

This bug is of course not too much of a problem when using the tool, it is only about retrieving the version number, after all, and there are other ways to obtain that information, but I thought I should report it here anyway.

**Comment by feross** [comment]
Thanks for the report. This is fixed in 2.0.4
